[alias]
paperclip = "clippy -F bootimage --release"
did-i-break-anything = "test -F bootimage --release"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-sunflower.json"

[target.x86_64-sunflower]
runner = "bootimage runner"
