# Fix imports
group_imports = "StdExternalCrate"
imports_granularity = "Module"

# Enable every once and a while to check for any line overflows
#error_on_line_overflow = true
#error_on_unformatted = true

# Align everything
tab_spaces = 6
wrap_comments = true
max_width = 80
inline_attribute_width = 80
struct_field_align_threshold = 80
enum_discrim_align_threshold = 80
short_array_element_width_threshold = 80

# Latest edition
edition = "2024"
style_edition = "2024"

# Misc
newline_style = "Unix"
binop_separator = "Back"
fn_params_layout = "Compressed"
use_field_init_shorthand = true
format_macro_matchers = false
