[package]
name = "libutil"
description = "A library for some useful utilities used by sunflower"
version = "0.1.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/janicria/sunflower"
